version: '3.1'
services:
  webapp:
    image: ubuntu
    restart: always
    environment:
    - POSTGRES_HOSTNAME=iriusprod
    - POSTGRES_USER=iriusprod
    - POSTGRES_PASSWORD=iriusprod
    ports:
    - 80:8080
    working_dir: /opt/app
    depends_on:
    - iriusprod
    networks:
    - aws-network

  iriusprod:
    image: postgres
    environment:
    - POSTGRES_USER=iriusprod
    - POSTGRES_PASSWORD=iriusprod
    volumes:
    - iriusprod:/data/db
    restart: always
    networks:
    - aws-network
volumes:
  iriusprod:
    driver: local

networks:
  aws-network:
    driver: bridge
